//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_bus
    {
        public int B_id { get; set; }
        public string B_name { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Available_Seats { get; set; }
        public Nullable<int> R_id { get; set; }
        public string Day { get; set; }
    
        public virtual Table_day Table_day { get; set; }
        public virtual Table_route Table_route { get; set; }
    }
}
