//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_route
    {
        public Table_route()
        {
            this.Table_bus = new HashSet<Table_bus>();
            this.Table_day = new HashSet<Table_day>();
        }
    
        public int R_id { get; set; }
        public Nullable<int> S_id { get; set; }
        public Nullable<int> D_id { get; set; }
        public string R_name { get; set; }
    
        public virtual ICollection<Table_bus> Table_bus { get; set; }
        public virtual ICollection<Table_day> Table_day { get; set; }
    }
}
