//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_booked
    {
        public int Booked_id { get; set; }
        public string Seat_No { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Id { get; set; }
    }
}
